### ISSUE TITLE
[bugreport]: KelpPlayer#setTabListName only works one time

### ISSUE THREAD

**Issue by DSeeLPYT** [PXAV/kelp#28]
### Describe the bug
When the Player gets another prefix you need to restart the server. Because KelpPlayer#setTabListName not working. and not updates. A rejoin not helped.

### What would you expect to happen?
The Tablistname should change.

### Environment information
* Operating system: Windows 10 20H1
* Java-Version: 1.8
* Kelp-Core-Version: v.0.0.3
* Version-Implementation: 1.8

**Comment by PXAV** [comment]
Thank you for your bug report. I have to test this out myself but I suppose it is not a Kelp issue, but a bug in spigot itself. This method is simply a wrapper for the bukkit method: 
```java
@Override
public void setPlayerTabListName(Player player, String tabListName) {
  player.setPlayerListName(tabListName);
}
```
> Extract from the player version implementation for 1.8

Try out using the method from bukkit directly by replacing your line with 
```java
kelpPlayer.getBukkitPlayer().setPlayerListName(name);
```
If the behavior does not change, it is a limitation set by spigot. 

For the future, I will implement a method for this purpose in the scoreboard system and let player tablist names be controlled via scoreboard teams as this is the only way I know how tablist names can be updated instantly.
