### ISSUE TITLE
[feat]: KelpEvents

### ISSUE THREAD

**Issue by DSeeLPYT** [PXAV/kelp#29]
**Describe the solution you'd like**
Events like KelpPlayerSidebarUpdate or Render Event. With this you can get the scoreboard which the player has.

**Comment by PXAV** [comment]
Thank you for your idea! Actually, I've been working on some custom events and listener handling for Kelp during the past few days. I will definitely add some custom events including sidebars, inventories, player settings, etc. They will come with the next release (0.0.4).
