### ISSUE TITLE
Make inventories reusable for multiple players

### ISSUE THREAD

**Issue by DSeeLP** [PXAV/kelp#44]
**Is your feature request related to a problem? Please describe.**
For every Widget that needs a player you need to call the Widget#player method. With this setup Inventories/Widgets can't be reused.

**Describe the solution you'd like**
A player parameter would be added to the KelpInventory#render and Widget#render method so the inventory can be reused.

**Comment by PXAV** [comment]
Hi, yes you are right that would be a cleaner design and I initially planned to do it like this. But if the `KelpPlayer` was passed on render, it would be more difficult to create widget-bound listeners. Currently, they are registered before the widget is actually rendered. I'll look at what can be done.

If you have an idea about how this can be solved, I would appreciate a comment.
