### ISSUE TITLE
[bugreport]: KelpItem#getItemStack returns an ItemStack without the Description/Lore

### ISSUE THREAD

**Issue by DSeeLP** [PXAV/kelp#45]
### Describe the bug
KelpItem#getItemStack returns an ItemStack without the Description/Lore.

### What do we have to do to reproduce this bug? 
1. Provide an item description to a KelpItem.
2. Check if the ItemStack returned has a lore.

### What would you expect to happen?
The returned ItemStack should contain a lore.

### Environment information
* Operating system: Linux Ubuntu 20.10
* Java-Version: 1.8
* Kelp-Core-Version: v.0.2.0
* Version-Implementation: 1.8

**Comment by PXAV** [comment]
Oh damn, I simply forgot to put the lore rendering process into the `#getItemStack()` method. Well, that's stupid ^^

Thank you for the bug report, will be fixed with the next release.
