### ISSUE TITLE
Redundant Precondition

### ISSUE THREAD

**Issue by QetzDev** [PXAV/kelp#5]
Hey,

I'm not sure if I'm right, but I tell you anway. 
Don't you have a redundant Preconditions at [VersionBinderModule](https://github.com/PXAV/kelp/blob/2313a963f33b8b6bcd2bad5434aac6bc3bfc35f5/core/src/main/java/de/pxav/kelp/core/application/inject/VersionBinderModule.java#L35) in line 65? You check in the line above if it is null.

**Comment by PXAV** [comment]
Yes I should do the check with the Preconditions before the if-statement and then remove the null check from it. Will be improved soon, thank you for your feedback :)

**Comment by QetzDev** [comment]
You're welcome :)
