### ISSUE TITLE
Read nbt Tags in KelpItem

### ISSUE THREAD

**Issue by DSeeLP** [PXAV/kelp#50]
**Is your feature request related to a problem? Please describe.**
At the moment you can only add and remove nbt tags. But you can't get the nbt Tags. For example i want to store an id as an nbt tag so i can identify that item. The problem is i can't read it later, when i get the kelp item from the itemstack in the inventory of the player.

**Describe the solution you'd like**
A method like hasTag(String tag) to check if the item has the tag and something like getTag(String tag) that returns the tag or null.

**Comment by PXAV** [comment]
Thank you for the feature request, those methods have already been implemented in the version template for items, so it shouldn't be a problem to port them over to `KelpItem` (pretty dumb I haven't done that already xD) Will be released in `0.3.3` together with the regions update.
